# Generated by Django 5.0 on 2023-12-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_word_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='words',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
